version: '3.8'

services:
  # Backend сервис
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: cv-backend
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - CONTACT_EMAIL=${CONTACT_EMAIL}
    networks:
      - cv-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend сервис
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    container_name: cv-frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://backend:5000/api
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - cv-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  cv-network:
    driver: bridge
