version: '3.8'

services:
  # Reverse proxy с SSL
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: cv-nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./ssl-certs:/etc/nginx/certs:ro
      - ./nginx-vhost:/etc/nginx/vhost.d
      - ./nginx-html:/usr/share/nginx/html
    networks:
      - cv-network

  # Let's Encrypt для автоматических SSL сертификатов
  letsencrypt:
    image: nginxproxy/acme-companion:latest
    container_name: cv-letsencrypt
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ssl-certs:/etc/nginx/certs:rw
      - ./nginx-vhost:/etc/nginx/vhost.d
      - ./nginx-html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
    depends_on:
      - nginx-proxy
    networks:
      - cv-network

  # Backend сервис
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: cv-backend
    restart: unless-stopped
    expose:
      - "5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - FRONTEND_URL=https://${DOMAIN}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - CONTACT_EMAIL=${CONTACT_EMAIL}
      - VIRTUAL_HOST=api.${DOMAIN}
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=api.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - cv-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend сервис
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    container_name: cv-frontend
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - cv-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  cv-network:
    driver: bridge

volumes:
  ssl-certs:
  nginx-vhost:
  nginx-html:
